/**
 * Utility functions for Solution Setup Step
 * Central export point for all utility functions
 */

// Name generation utilities
export {
  generateInternalName,
  generatePrefix,
  validateInternalName,
  validatePrefix,
  generateSolutionInternalName,
  generatePublisherInternalName,
  cleanInternalName,
  cleanPrefix,
  isAutoGeneratedName,
  suggestAlternativeName,
  suggestAlternativePrefix,
} from './nameGenerators';

// Search and filtering utilities
export {
  filterItems,
  filterPublishers,
  filterSolutions,
  highlightSearchTerm,
  sortByRelevance,
  createSearchDebouncer,
  validateSearchTerm,
  createPublisherSearchConfig,
  createSolutionSearchConfig,
  groupSearchResults,
} from './searchFilters';

// Validation utilities
export {
  DEFAULT_VALIDATION_RULES,
  validateSolutionName,
  validateSolutionInternalName,
  validatePublisherDisplayName,
  validatePublisherInternalName,
  validatePublisherPrefix,
  validateSolutionSetupForm,
  validateNewPublisherForm,
  hasErrorType,
  getFieldErrors,
  getFirstFieldError,
  createValidationSummary,
  validateSingleField,
} from './validationRules';
