name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - 'feature/**'
      - 'bugfix/**'
      - 'hotfix/**'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        id: npm-cache
        with:
          path: ./node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Npm install
        run: npm install
        if: steps.npm-cache.outputs.cache-hit != 'true'
      - name: Run unit tests
        run: npm run test:unit
